version: "3.7"

services:
  frontend:
    build: ../React
    restart: always
    ports:
      - "3000:80"
    links:
      - backend

  backend:
    build: ../Node
    restart: always
    ports:
      - "4000:3000"
    volumes:
      - ./.db:/app/src/.db
